
export const CATEGORIES = [
    { value: 'general', label: 'General' },
    { value: 'business', label: 'Negocios' },
    { value: 'entertainment', label: 'Entretenimiento' },
    { value: 'health', label: 'Salud' },
    { value: 'science', label: 'Ciencia' },
    { value: 'sports', label: 'Deportes' },
    { value: 'technology', label: 'Tecnología' },
]

export const COUNTRIES = [
    { value: 'ar', label: 'ar - Argentina' },
    { value: 'au', label: 'au - Australia' },
    { value: 'at', label: 'at - Austria' },
    { value: 'be', label: 'be - Belgica' },
    { value: 'br', label: 'br - Brazil' },
    { value: 'bg', label: 'bg - Bulgaria' },
    { value: 'ca', label: 'ca - Canadá' },
    { value: 'cn', label: 'cn - China' },
    { value: 'co', label: 'co - Colombia' },
    { value: 'cu', label: 'cu - Cuba' },
    { value: 'cz', label: 'cz - Republica Checa' },
    { value: 'eg', label: 'eg - Egipto' },
    { value: 'fr', label: 'fr - Francia' },
    { value: 'de', label: 'de - Alemania' },
    { value: 'gr', label: 'gr - Grecia' },
    { value: 'hk', label: 'hk - Hong Kong' },
    { value: 'in', label: 'in - India' },
    { value: 'id', label: 'id - Indonesia' },
    { value: 'ie', label: 'ie - Irlanda' },
    { value: 'il', label: 'il - Israel' },
    { value: 'it', label: 'it - italia' },
    { value: 'jp', label: 'jp - Japón' },
    { value: 'lv', label: 'lv - Latvia' },
    { value: 'my', label: 'my - Malasia' },
    { value: 'mx', label: 'mx - Mexico' },
    { value: 'ma', label: 'ma - Marruecos' },
    { value: 'nl', label: 'nl - Países Bajos' },
    { value: 'nz', label: 'nz - Nueva Zelanda' },
    { value: 'ng', label: 'ng - Nigeria' },
    { value: 'no', label: 'no - Noruega' },
    { value: 'ph', label: 'ph - Filipinas' },
    { value: 'pl', label: 'pl - Polonia' },
    { value: 'pt', label: 'pt - Portugal' },
    { value: 'ro', label: 'ro - Rumania' },
    { value: 'ru', label: 'ru - Rusia' },
    { value: 'sa', label: 'sa - Arabia Saudita' },
    { value: 'rs', label: 'rs - Serbia' },
    { value: 'sg', label: 'sg - Singapur' },
    { value: 'sk', label: 'sk - Eslovaquia' },
    { value: 'si', label: 'si - Eslovenia' },
    { value: 'za', label: 'za - Sudáfrica' },
    { value: 'kr', label: 'kr - Corea del Sur' },
    { value: 'se', label: 'se - Suecia' },
    { value: 'ch', label: 'ch - Suiza' },
    { value: 'tw', label: 'tw - Taiwan' },
    { value: 'th', label: 'th - Tailandia' },
    { value: 'tr', label: 'tr - Turquía' },
    { value: 'ae', label: 'ae - Emiratos Árabes Unidos' },
    { value: 'ua', label: 'ua - Ucrania' },
    { value: 'uk', label: 'uk - Reino Unido' },
    { value: 'us', label: 'us - Estados Unidos' },
    { value: 've', label: 've - Venezuela' },
];